# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_second_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Second_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_Class', models.CharField(max_length=100)),
                ('N_name', models.CharField(max_length=100)),
                ('N_num', models.CharField(max_length=100)),
                ('N_content', models.CharField(max_length=150)),
                ('N_handle', models.CharField(max_length=100)),
            ],
        ),
    ]
